baseURL = "https://example.org"
theme = "hugo_theme_adam_eve"
DefaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[Languages]

[Languages.en]
languageCode = "en"
title = "Remarques"

[Languages.en.params]
description = "Notes about anything"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "tango"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
